# ===================================================================
# Model Definitions
# ===================================================================
# This section acts as a database for all available Gemini models.
# The manager will use this data to enforce rate limits and check capabilities.
models:
  gemini-2.5-pro:
    rpm: 5
    tpm: 250000
    rpd: 100
    inputs: [ "audio", "image", "video", "text", "pdf" ]
    outputs: [ "text" ]
    tokens:
      input_limit: 1048576
      output_limit: 65536
    capabilities:
      thinking: true
      function_calling: true
      code_execution: true
      structured_outputs: true
      caching: true
      search_grounding: true

  gemini-2.5-flash:
    rpm: 10
    tpm: 250000
    rpd: 250
    inputs: [ "text", "image", "video", "audio" ]
    outputs: [ "text" ]
    tokens:
      input_limit: 1048576
      output_limit: 65536
    capabilities:
      thinking: true
      function_calling: true
      code_execution: true
      structured_outputs: true
      caching: true
      search_grounding: true

  gemini-2.5-flash-lite:
    rpm: 15
    tpm: 250000
    rpd: 1000
    inputs: [ "text", "image", "video", "audio", "pdf" ]
    outputs: [ "text" ]
    tokens:
      input_limit: 1048576
      output_limit: 65536
    capabilities:
      thinking: true
      function_calling: true
      code_execution: true
      structured_outputs: true
      caching: true
      search_grounding: true
      url_context: true

  gemini-2.0-flash:
    rpm: 15
    tpm: 1000000
    rpd: 200
    inputs: [ "audio", "image", "video", "text" ]
    outputs: [ "text" ]
    tokens:
      input_limit: 1048576
      output_limit: 8192
    capabilities:
      thinking: "experimental" # Use string for non-boolean values
      function_calling: true
      code_execution: true
      structured_outputs: true
      caching: true
      live_api: true
      search: true

  gemini-2.0-flash-lite:
    rpm: 30
    tpm: 1000000
    rpd: 200
    inputs: [ "audio", "image", "video", "text" ]
    outputs: [ "text" ]
    tokens:
      input_limit: 1048576
      output_limit: 8192
    capabilities:
      function_calling: true
      structured_outputs: true
      caching: true
      batch_api: true

  
# ===================================================================
# Task Definitions
# ===================================================================
tasks:

    models:
      - gemini-2.5-flash        # Best price-performance fallback
      - gemini-2.5-flash-lite     # Most cost-efficient fallback
      - gemini-2.0-flash-lite     # Final cost-efficient option
      - gemini-2.0-flash          # High throughput fallback
      - gemini-2.5-pro            # Highest quality, best one
      

